[build]
  command = "npm run build"
  publish = ".next"
  # Base directory for the frontend application
  base = "frontend"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions" # Optional: if you have serverless functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false # Ensure client-side routing works

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-ancestors 'self';"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cache-Control = "public, max-age=31536000, immutable" # Aggressive caching for static assets

# Force cache invalidation
[build.environment]
  NETLIFY_CACHE_VERSION = "2"