[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://ototakibim-mvp.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"